title: Jackson Eshbaugh
email: eshbaugj@lafayette.edu
description: "Jackson Eshbaugh is a computer science and French student at Lafayette College. His research explores machine learning interpretability and multilingual NLP, with a focus on understanding language through computational methods."
baseurl: ""
url: "https://jacksoneshbaugh.github.io"
twitter_username: jacksoneshbaugh
github_username: jacksoneshbaugh
linkedin_username: jacksoneshbaugh

author:
  name: Jackson Eshbaugh
  email: eshbaugj@lafayette.edu

header_pages:
  - about.md
  - research.md
  - teaching.md
  - resume.md
  - contact.md

minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/jacksoneshbaugh" }
    - { platform: x, user_url: "https://twitter.com/jacksoneshbaugh" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jacksoneshbaugh/" }

theme: minima
plugins:
  - jekyll-feed

feed:
  path: blog/atom.xml
  posts_limit: 10

sass:
  sass_dir: _sass
  sourcemap: never